/**
 * Capability scaffolding generator. Produces the source text for a new
 * capability following the module conventions, plus a test skeleton and a
 * risk-assessment document, everything a Creator Mode proposal needs.
 * Pure string generation: no IO, fully unit-testable.
 */

export interface ScaffoldSpec {
  module: string;
  action: string;
  title: string;
  intent: string;
  risk: "read" | "write" | "money" | "identity" | "destructive" | "secret";
  permission: string;
  inputFields: { name: string; type: "string" | "number" | "boolean"; description?: string }[];
}

const zodTypeFor = (t: ScaffoldSpec["inputFields"][number]["type"]): string =>
  t === "string" ? "z.string()" : t === "number" ? "z.number()" : "z.boolean()";

export function renderCapabilitySource(spec: ScaffoldSpec): string {
  const fields = spec.inputFields
    .map(
      (f) =>
        `      ${f.name}: ${zodTypeFor(f.type)}${f.description ? `.describe(${JSON.stringify(f.description)})` : ""},`,
    )
    .join("\n");
  const capId = `${spec.module}.${spec.action}`;
  return `import { z } from "zod";
import type { Database } from "@chaste/db";
import { defineCapability, type CapabilityRegistry } from "@chaste/kernel";

export interface ModuleDeps {
  db: Database["db"];
}

// Generated by Creator Mode scaffold; reviewed as a governed proposal.
const ${spec.action} = (deps: ModuleDeps) =>
  defineCapability({
    id: "${capId}",
    title: ${JSON.stringify(spec.title)},
    intent: ${JSON.stringify(spec.intent)},
    module: ${JSON.stringify(spec.module)},
    risk: ${JSON.stringify(spec.risk)},
    permission: ${JSON.stringify(spec.permission)},
    input: z.object({
${fields}
    }),
    output: z.object({ ok: z.boolean() }),
    execute: async (ctx, input) => {
      // TODO(proposal): implement against deps.db within ctx.actor.orgId scope.
      void deps;
      void input;
      return { ok: true };
    },
  });

export function register${cap(
  spec.module,
)}Capabilities(registry: CapabilityRegistry, deps: ModuleDeps): void {
  registry.register(${spec.action}(deps));
}
`;
}

function cap(module: string): string {
  return module
    .split(/[-_]/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

export function renderTestSkeleton(spec: ScaffoldSpec): string {
  const capId = `${spec.module}.${spec.action}`;
  return `import { describe, expect, it } from "vitest";

describe("${capId}", () => {
  it("conforms to the capability contract", async () => {
    const { assertWellFormedCapability } = await import("@chaste/kernel");
    // Import the registered capability here once wired into its module.
    expect(true).toBe(true); // placeholder replaced by proposal tests
  });
});
`;
}

export function renderRiskDoc(spec: ScaffoldSpec): string {
  const inverseNote =
    spec.risk === "read"
      ? "Read-only: no state changes, no inverse needed."
      : spec.risk === "destructive" || spec.risk === "identity"
        ? `Always human-approved (${spec.risk} class). Inverse must be declared before merge.`
        : `${spec.risk}-class: declare an inverse or justify the conformance warning in review.`;
  return `# Risk assessment: ${spec.module}.${spec.action}

- Risk class: ${spec.risk}
- Required permission: ${spec.permission}
- Blast radius: scoped to org rows via ctx.actor.orgId.
- Reversibility: ${inverseNote}
- Money handling: ${
    spec.risk === "money"
      ? "amounts in integer minor units; policy thresholds apply."
      : "no direct money movement."
  }
- Reviewer checklist:
  - [ ] Input schema rejects hostile values
  - [ ] Org scoping on every query
  - [ ] Ledger writes balanced (if any)
  - [ ] Tests cover failure paths
`;
}

export function renderProposalDiff(spec: ScaffoldSpec, filePath: string): string {
  const src = renderCapabilitySource(spec);
  const body = src
    .split("\n")
    .map((l) => `+${l}`)
    .join("\n");
  return `--- /dev/null
+++ b/${filePath}
@@ -0,0 +1,${src.split("\n").length} @@
${body}`;
}
