// Package apicontract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apicontract

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// GoPolicyResponse defines model for GoPolicyResponse.
type GoPolicyResponse struct {
	CanEdit bool   `json:"canEdit"`
	Policy  Policy `json:"policy"`
}

// Policy defines model for Policy.
type Policy struct {
	MaxRiskAutonomous   string  `json:"maxRiskAutonomous"`
	MoneyThresholdMinor int64   `json:"moneyThresholdMinor"`
	RequiresApprovalFor RawJSON `json:"requiresApprovalFor"`
}
