import * as echarts from "echarts";
import { z } from "zod";

/** A chart is a constrained spec over the section's own frame, never free-form option JSON. */
export const chartSpecSchema = z.object({
  type: z.enum(["bar", "line", "area", "pie"]),
  title: z.string().max(160).optional(),
  /** Category column (x axis / pie names). */
  x: z.string().min(1),
  /** Value columns (y series / pie values use only the first). */
  y: z.array(z.string().min(1)).min(1).max(3),
});

export type ChartSpec = z.infer<typeof chartSpecSchema>;

const WIDTH = 640;
const HEIGHT = 360;

/** Renders a chart to a standalone SVG string via ECharts server-side rendering. */
export function renderChartSvg(spec: ChartSpec, rows: Record<string, unknown>[]): string | null {
  if (rows.length === 0) return null;
  const categories = rows.map((r) => String(r[spec.x] ?? ""));
  let series: Record<string, unknown>[];
  if (spec.type === "pie") {
    const valueCol = spec.y[0]!;
    series = [
      {
        type: "pie",
        radius: "62%",
        data: rows.map((r) => ({ name: String(r[spec.x] ?? ""), value: Number(r[valueCol] ?? 0) })),
        label: { formatter: "{b}: {c}" },
      },
    ];
  } else {
    series = spec.y.map((col) => ({
      name: col,
      type: spec.type === "area" ? "line" : spec.type,
      ...(spec.type === "area" ? { areaStyle: {}, stack: "total" } : {}),
      data: rows.map((r) => Number(r[col] ?? 0)),
    }));
  }
  const chart = echarts.init(null, null, { renderer: "svg", ssr: true, width: WIDTH, height: HEIGHT });
  try {
    chart.setOption({
      title: spec.title ? { text: spec.title, left: "center", textStyle: { fontSize: 13 } } : undefined,
      legend: spec.y.length > 1 && spec.type !== "pie" ? { bottom: 0 } : undefined,
      grid: { left: 48, right: 16, top: spec.title ? 40 : 24, bottom: spec.y.length > 1 && spec.type !== "pie" ? 36 : 28 },
      ...(spec.type === "pie"
        ? {}
        : {
            xAxis: { type: "category", data: categories },
            yAxis: { type: "value" },
          }),
      series,
    });
    return chart.renderToSVGString();
  } finally {
    chart.dispose();
  }
}

function esc(v: unknown): string {
  return String(v ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

export interface ReportSection {
  heading: string;
  columns: string[];
  rows: Record<string, unknown>[];
  svg: string | null;
}

/**
 * Builds the downloadable artifact: one self-contained HTML document
 * (inline styles, inline SVG) that prints cleanly to PDF from any browser.
 * Deterministic and synchronous; no JS shipped inside the report.
 */
export function renderReportHtml(
  title: string,
  region: string | null,
  narrative: string | null,
  sections: ReportSection[],
): string {
  const body = sections
    .map((s) => {
      const table = `
      <table>
        <thead><tr>${s.columns.map((c) => `<th>${esc(c)}</th>`).join("")}</tr></thead>
        <tbody>
          ${s.rows
            .map(
              (r) =>
                `<tr>${s.columns.map((c) => `<td>${esc(typeof r[c] === "number" ? r[c] : (r[c] ?? ""))}</td>`).join("")}</tr>`,
            )
            .join("\n")}
        </tbody>
      </table>`;
      return `
      <section>
        <h2>${esc(s.heading)}</h2>
        ${s.svg ? `<div class="chart">${s.svg}</div>` : ""}
        ${s.rows.length === 0 ? `<p class="empty">No data for this selection.</p>` : table}
      </section>`;
    })
    .join("\n");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${esc(title)}</title>
<style>
  :root { color-scheme: light; }
  body { font-family: ui-sans-serif, system-ui, sans-serif; margin: 40px auto; max-width: 760px; color: #1c1917; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  .meta { color: #78716c; font-size: 12px; margin-bottom: 24px; }
  .narrative { background: #fafaf9; border: 1px solid #e7e5e4; border-radius: 8px; padding: 12px 16px; margin-bottom: 24px; }
  section { margin-bottom: 32px; page-break-inside: avoid; }
  h2 { font-size: 15px; margin-bottom: 10px; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th, td { border: 1px solid #e7e5e4; padding: 6px 10px; text-align: left; }
  th { background: #fafaf9; font-weight: 600; }
  td { font-variant-numeric: tabular-nums; }
  .chart svg { max-width: 100%; height: auto; }
  .empty { color: #a8a29e; font-style: italic; }
</style>
</head>
<body>
<h1>${esc(title)}</h1>
<p class="meta">Generated by ChasteBusinessOS on ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC · Data region: ${esc(region ?? "unspecified")}</p>
${narrative ? `<div class="narrative">${esc(narrative)}</div>` : ""}
${body}
</body>
</html>`;
}
